config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, length: { in: 1..200 }
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
        validates :name, presence: true, uniqueness:true, length: {in: 2..20}
        validates :introduction,length: { maximum: 50}


        devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        attachment :profile_image
        has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  
  def after_sign_in_path_for(resource)
    user_path(resource) # ログイン後に遷移するpathを設定
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :editing_user, only: [:edit]

  def new
    @book = Book.new
  end

  def create
    @booknew = Book.new(book_params) 
    @booknew.user_id =  current_user.id 
    @user = current_user
  if @booknew.save 
    redirect_to book_path(@booknew.id), notice: 'Book was successfully created'  
  else
    @books = Book.all
    render :index
  end
end

  def index
    @books = Book.all
    @booknew = Book.new
    @user = current_user
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated!'
    else
      
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def editing_user
    book = Book.find(params[:id])
    if book.user != current_user 
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @booknew = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @booknew = Book.new
  
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
  else
    redirect_to user_path(current_user)
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice: 'Book was successfully updated!'
    else
      render :edit
  end
end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
<div class="error">
<h4><%= pluralize(model.errors.count,"error") %> prohibited this product from being saved:</h4>

<ul><% model.errors.full_messages.each do |message| %>
<li class="error-message"><%= message %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/books/_form.html.erb
  <h2 class="mt-3">New book</h2>
    <%= form_with model:book, local:true do |f| %>
<div class="form-group">
  <label>Title</label>
  <%= f.text_field :title, class:"form-control" %>
</div>

<div class="form-group">
  <label>Opinion</label>
  <%= f.text_area :body, class:"form-control book_body" %>
</div>

<div class="form-group">
  <%= f.submit btn, class:"btn btn-success col-xs-12" %>
</div>
<% end %>

app/views/books/_link.html.erb
<h2>User info</h2>

<h2>New Books</h2>
<%= form_with model:@book, local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= render 'books/error', model: @book %>

      <table>
            <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit btn: "Update Book", class:"btn btn-success col-xs-12" %>
        </div>
            <% end %>
        <td class="show"><%= link_to "Show", book_path(@book.id) %></td>
        <td>|</td>
        <td class="back"><%= link_to "Back", books_path %></td>
      </table>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <table class='table'>
                <%= render 'users/profile', user: @user %>
            </table>
                <%= render 'books/error', model: @booknew %>
            <div>
                <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
            </div>
        </div>

        <div class='col-md-8 offset-md-1'>
            <h2>Books</h2>
            <table class="table table-hover table-invers">
            <thead>
                <th></th>
                <th>title</th>
                <th>opinion</th>
                <th colspan="3"></th>
                <% @books.each do |book| %>
                <tr><td>
                <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: "40x40",fallback: "no_image.jpg"%>
                    <% end %></td>
                    <td><%= link_to book.title, book_path(book.id) %></td>
                    <td><%= book.body %></td>
                    </tr>
                <% end %>
            </table>
        </div>
            </tr>
            </thead>
            </tbody>
            </table>
        </div>
        </div>
        </div>
    </div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <table class='table'>
          <%= render 'users/profile', user: @user %>
      </table>

        <div>
          <tr><%= render 'books/form', {book:@booknew, btn: 'Create Book'} %></tr>
        </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <table class="table table-user-show">
      <tr>
      <h2>Book detail</h2>
      <tbody>
      </tr>
      <td><%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg"%><br>
          <% end %>
          <%= link_to @user.name, user_path(@user) %>
      </td>
      <td><%= link_to @book.title %></td>
      <td><%= @book.body %></td>
      <% if @book.user_id == current_user.id %>
      <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
      <td><%= link_to "Destroy", book_path, method: :delete, class:"btn btn-sm btn-danger", "data-confirm"=> "Are you sure?" %></td>
          <% end %>
      </tr>
      </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class='container'>
    <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
    </div>
</main>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if user.errors.any? %>
<h4><%= pluralize(user.errors.count,"error") %> prohibited this product from being saved:</h4>
<% user.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track' %>
  </head>

  <body>
  <header>
  <% if flash[:alert] %>
    <div class="notification is-denger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

    <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><span>Bookers</span></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
<% if user_signed_in? %>
      <li><a class="fas fa-home nav-link text-light" href="<%= user_path(current_user.id) %>"> home</a></li>
      <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
      <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
      
      <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
    <% else %>
      <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
      <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
      <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
      <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
    <% end %>
        </ul>
      </div>
    </div>
    </nav>
    </header>
    <%= yield %>
        <footer class="footer">
  <div class='container mt-5'>
  <div class='row'>
	<div class='mx-auto'>
		<p>CopyRight Infratop.inc</p>
	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_profile.html.erb
<table class="table table-user">
    <h2>User info</h2>
		<tr><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></tr>
		<tr>
		  <th>name</th>
		  <th><%= user.name %></th>
		</tr>
		
		<div class="form-body row">
    <tr><th>introduction</th>
		<th><%= user.introduction %></th></tr>
		</div>
		</table>

<%# 編集ボタンについて %>
<%# <% if user.id == current_user.id %> 
<div class="row">
<td><%= link_to " ", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %></td>
<%# <% else %>
<%# <td><%= link_to " ", user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
<%# <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div class="notification is-danger">
<h4><%= pluralize(@user.errors.count,"error") %> prohibited this product from being saved:</h4>
<% @user.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
</div>
<% end %>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
          <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
              <label>name</label>
              <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
                <label>Image</label>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form-group">
              <label>introduction</label>
              <%= f.text_area :introduction, class:"form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      
      
      <table class="table">
      <tr><%= render 'users/profile', user: @user %></tr>
      </table>
      
      <div>
        <%= render 'books/form', {book: @booknew, btn: 'Create Book'} %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
	    <h2>Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th clspan="3"></th>
      </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "40x40",fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", "/users/#{user.id}" %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</main>

app/views/users/show.html.erb
  
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

        <table class='table'>
          <tr><%= render 'users/profile', user: @user %></tr>
        </table>

        
      <div>
        <tr><%= render 'books/form', {book: @booknew, btn: 'Create Book'} %></tr>
      </div>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40",fallback: "no_image.jpg"%>
            <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </table>
          </tr>
        
        </table>
    </div>
  </div>
</div>